name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - pip:
    - transformers
    - transformers[sentencepiece]
    - datasets
    - sacrebleu
    - rouge_score
    - pyYAML
    - py7zr
    - numpy
    - nltk
    - tqdm
    - pandas
    - tqdm
    - matplotlib
    - torch
    - torchvision
    - notebook
    - ensure
    - fastapi
    - uvicorn
    - Jinja2
    - boto3
    - mypy-boto3-s3
    - python-box